projectName: ohutils
# From: https://github.com/serverless-nextjs/serverless-next.js#concatenating-environment-variables-doesnt-seem-to-work
stage: ${env.STAGE}
myNextApplication:
  component: '@sls-next/serverless-component@latest'
  inputs:
    domain: ${env.DOMAIN}
    build:
      cmd: yarn
    roleArn: ${env.ROLE_ARN}
    bucketName: ${projectName}-${stage}
    name:
      defaultLambda: ${projectName}-${stage}-default-lambda
      apiLambda: ${projectName}-${stage}-api-lambda
      imageLambda: ${projectName}-${stage}-image-lambda
      regenerationLambda: ${projectName}-${stage}-regeneration-lambda
    cloudfront:
      # You need add maintenance bucket to origin and set behaviour yourself.
      errorPages:
        - code: 403
          path: '/maintenance.html'
          minTTL: 1
          responseCode: 503
