name: Continuous deploy

on:
  push:
    branches:
      - release

jobs:
  serverless-deploy:
    runs-on: ubuntu-latest

    env:
      # From: https://github.com/actions/checkout/issues/440#issuecomment-854240996
      AWS_EC2_METADATA_DISABLED: true

      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

      URL: ${{secrets.URL}}
      DB_VERSION: ${{secrets.DB_VERSION}}
      DB_HOST: ${{secrets.DB_HOST}}
      DB_PORT: ${{secrets.DB_PORT}}
      DB_NAME: ${{secrets.DB_NAME}}
      DB_USER: ${{secrets.DB_USER}}
      DB_PASS: ${{secrets.DB_PASS}}
      NEXT_PUBLIC_TRACKING_CODE: ${{secrets.NEXT_PUBLIC_TRACKING_CODE}}
      GOOGLE_CLIENT_ID: ${{secrets.GOOGLE_CLIENT_ID}}
      GOOGLE_CLIENT_SECRET: ${{secrets.GOOGLE_CLIENT_SECRET}}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: yarn install --immutable

      - name: Download `.serverless` state from S3
        run: aws s3 sync s3://ohutils-serverless/production/.serverless .serverless --delete

      - name: Deploy to AWS
        uses: serverless/github-action@master

      - name: Upload `.serverless` state to S3
        run: aws s3 sync .serverless s3://ohutils-serverless/production/.serverless --delete
