name: Continuous deploy

on:
  push:
    branches:
      - production

jobs:
  serverless-deploy:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: production
      # From: https://github.com/actions/checkout/issues/440#issuecomment-854240996
      AWS_EC2_METADATA_DISABLED: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Set STAGE environment
        run: echo "STAGE=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
      - name: Set SECRETS_KEY environment
        run: echo "SECRETS_KEY=${STAGE}_secrets" >> $GITHUB_ENV
      - name: Mask secrets
        run: yarn maskSecrets "${{secrets[env.SECRETS_KEY]}}"
      - name: Set secrets to env
        run: echo "${{secrets[env.SECRETS_KEY]}}" >> $GITHUB_ENV

      - name: Download `.serverless` state from S3
        run: aws s3 sync s3://${{env.PROJECT_NAME}}-serverless/${{env.STAGE}}/.serverless .serverless --delete

      - name: Deploy to AWS
        uses: serverless/github-action@master

      - name: Upload `.serverless` state to S3
        run: aws s3 sync .serverless s3://${{env.PROJECT_NAME}}-serverless/${{env.STAGE}}/.serverless --delete
